### ISSUE TITLE
FlansMod Not Installing

### ISSUE THREAD

**Issue by TheSouthernerBrother** [Lebroncraft/crewmod#6]
So when I download the mod pack it displays flansmod and I drag it to the mods folder. However, no matter how many times I load flansmod even if it's from the website I will not get the weapon boxes or cars, only see the gun modifiers from tinkers construct.

**Comment by Mitsab** [comment]
you need to add the flan folder to your minecraft directory.

**Comment by TheSouthernerBrother** [comment]
I did, I added first the entire flansmod file, then after it didn't work I transferred all the .jar files into the mod so they are registered separately but still no result.
